name: Daily Job

on:
  schedule:
    # 每天 UTC 时间 10:00 运行
    - cron: "0 10 * * *"
  workflow_dispatch:  # 添加这个触发器来支持手动运行

jobs:
  sync-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
      

    - name: Install dependencies
      run: |
        conda install -y python=3.10 flake8 pytest requests numpy

    - name: Pull latest changes from external repository
      run: |
        git remote add upstream https://github.com/kimwang1978/collect-tv-txt.git || true
        git fetch upstream
        git merge upstream/main --allow-unrelated-histories -m "Merged updates from upstream"

    - name: Modify main.py variables
      run: |
        sed -i 's/^about_video2 = .*/about_video2 = ""/' main.py
        sed -i 's/^about = .*/about = ""/' main.py

    - name: Set git identity
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add main.py
        git commit -m "Updated main.py: Cleared about_video2 and about variables"
        git push origin HEAD

    - name: Lint with flake8
      run: |
        conda install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        conda install pytest
        pytest
